### ISSUE TITLE
Reveal less meta password info

### ISSUE THREAD

**Issue by samscott89** [rchatterjee/pam-typopw#12]
The current stored data leaks the password length and the entropy estimate. The former is leaked when the user accidentally enters a blank password (since the hamming distance is therefore the entire password length).

Options seem to be:
1. Make this data more granular (change hamming distance computation to 0-2 or 3+ or something).
2. Show formally why this is unimportant.

The entropy estimate, for example, could potentially lead to a knapsack-like problem. Suppose a naive implementation simply assigns an entropy estimate to each character independently, then the letters of the password could be recovered by solving the knapsack of these per-character weights.

**Comment by rchatterjee** [comment]
FIxed this in the [C++ version](https://github.com/rchatterjee/typtopcpp/edit/master/README.md).
