### ISSUE TITLE
word2keypress

### ISSUE THREAD

**Issue by pnueli** [rchatterjee/pam-typopw#2]
problem - the install script fails in installing word2keypress
"""
Installed /usr/local/lib/python2.7/dist-packages/adaptive_typo-1.0-py2.7.egg
Processing dependencies for adaptive-typo==1.0
Searching for word2keypress
Reading https://pypi.python.org/simple/word2keypress/
Best match: word2keypress 0.3
Downloading https://pypi.python.org/packages/36/5c/0b33769c91bca3cc59db091ff0c62deb088822900adc509bf29e9dce8cbd/word2keypress-0.3.tar.gz#md5=cb85ab3c2cf94ad6758fdbd26238f7bf
Processing word2keypress-0.3.tar.gz
Writing /tmp/easy_install-tFkpWR/word2keypress-0.3/setup.cfg
Running word2keypress-0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tFkpWR/word2keypress-0.3/egg-dist-tmp-Yg3X31
word2keypress/_keyboard.c:283:31: fatal error: numpy/arrayobject.h: No such file or directory
compilation terminated. """

solved it (for now) by downloading it manually via the website gui

**Comment by rchatterjee** [comment]
Pushed a fix. Works in my mac for this.
