### ISSUE TITLE
sh: 0: getcwd() failed

### ISSUE THREAD

**Issue by pnueli** [rchatterjee/pam-typopw#6]
This problem accured mid-correction of a different problem, so might not be relevent

sudo apt-get install sqlite3
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
aDAPTIVE pASSWORD: 
...
...
...

**Comment by rchatterjee** [comment]
I haven't seen this in a long while. So closing this for now.
